version: "3"
services:
  vscode-server:
    image: codercom/code-server
    ports:
      - "8080:8080"
    environment:
      - PASSWORD="setup"
    volumes:
      - /mnt/d/work:/work
    command: --auth none
    
    
  jlab:
    image: jupyter/datascience-notebook
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - /mnt/d/work:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
